title: "Nicholas Reich: Biostatistics and Infectious Disease Epidemiology"
description: "Reich Lab @ UMassAmherst"
author: "Nicholas Reich"
baseurl: ""
url: "http://reichlab.io/"

twitter_username: reichlab
github_username: reichlab
source_url: "https://github.com/reichlab/reichlab.github.io"

# Build settings
markdown: kramdown
sass:
  compressed: true
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - build.sh
  - Rakefile
  - deploy_key.enc
paginate: 5
paginate_path: "/page:num"
excerpt_separator: <!--more-->
gems:
  - jekyll-paginate
defaults:
  - scope:
      path: "blog/_posts"
    values:
      permalink: /:year/:month/:day/:title.html
  - scope:
      path: "talks/_posts"
    values:
      permalink: /talks/:title.html

# Preprocessing configuration
# BibTeX file names relative to `_data/bibtex_sources`
bibtex_sources:
  - reichlab-pub-list.bib

# GitHub research sources
# Local researches in `_research` are included automatically
research_sources:
  - reichlab/flusight

# GitHub teaching sources
# Local files in `_teaching` are included automatically
# teaching_sources:
  # - <>
